### ISSUE TITLE
Integrate local LLM e.g. Llama

### ISSUE THREAD

**Issue by Mearman** [shaunnarayan/cytev2#6]
Llama, Alpaca, Vicuna, other camelid related LLMs

**Comment by shaunnarayan** [comment]
> other camelid related LLMs

lol yup this is something I'm very keen on, but don't currently have enough understanding of to build. I'll start looking into it & report findings, if anyone else tracking this is experienced in the domain please jump in

**Comment by shaunnarayan** [comment]
@Mearman I've got a basic integration using [llama.cpp](https://github.com/ggerganov/llama.cpp) working on a [branch](https://github.com/shaunnarayan/cytev2/tree/llama)
Any llama.cpp compatible model local file path can now be supplied in settings instead of an OpenAI api key. I tried some [alpaca models](https://huggingface.co/Pi3141) which ran too. Not sure how to translate Vicuna weights to ggml format at the moment, but seems possible, would assume someone will upload to huggingface eventually.

Still need to polish up canceling in progress requests.

It's tough for me to iterate this quickly because I have a Macbook air M1 which runs alpaca 13B pretty slowly. I have a feeling the prompt will need tweaking to get good responses out of these distilled models, I asked it "What have I done today" as I do with GPT4, and it responded very literally, saying I've been running OCR and asking questions. Guess it wasn't wrong, lol.
